### ISSUE TITLE
(Rosefire v2) Protectecting users from developers

### ISSUE THREAD

**Issue by fisherds** [rockwotj/rose-firebase-auth#12]
So I'm sure this would be hard, but what makes OAuth 2.0 **work** is users don't have to give their password to the app's creators.  For example if I student team uses Google Login I don't even think twice about putting in my password.  I know that password goes to Google, then Google tells the app that I'm confirmed as really being that person.  The app developer never gets the user's password.

So when a student team makes an app I really don't want to use my real Rose-Hulman password.  To be honest it felt really awkward to do it with Tyler's app.  So it would be huge (and hard) if there was a way to insulate the password from the app developer.  I assume this would required a custom UI component specific to each platform that did a web view embed somehow.  (note, I don't care about scopes, I only want 1 scope)

To be honest, I'm worried that as soon as Firebase adds Email / Password verification, then I'll prefer that to Rosefire.  If someone confirms an @rose-hulman.edu email using a low tech "go check your email and click the Verify link" method, then that'll protect passwords from the app developer better.  I certainly prefer to use the Rosefire tool, but not at the risk of password thefts.

**Comment by rockwotj** [comment]
Is that something Firebase is going to add? Are you going to be able to limit the domain of of the email registration? 

I could make this an embedded web view and open up a webview to a login page on Rosefire (there would only be one scope). But that would complicate setup for developers, increasing the complexity. 

The same would have to go for web. It would be a pop-up similar to Google, doing web redirects would be much more difficult, and not something I would do at first.

Is this a big priority?

This would be an enhancement that would take a great deal of effort, especially to keep the developer experience as simple as possible.

**Comment by rockwotj** [comment]
What if in the meantime I give you a dummy account?

**Comment by fisherds** [comment]
I like dummy accounts for now.  It'd make people feel comfortable using someone else's app for sure. 

  As far as priorities go it's not a priority until it is a priority. :)  Yes, that's a joke, but it's not a priority until there is a next great tool out there.  Rosefire has the advantage of being an account we know for sure everyone has, so it's way better than Google, Facebook, or Github OAuth.  And it limits the users to Rose accounts in cases where that is important.  Then compare it to Email / Password login.  At present Rosefire is **WAY** better security than Firebase's email password which gets a -1 on security on a scale from 1 to 10.  I feel comfortable guessing that is a hole they will patch one day (probably soon).   So at present the priority of this feature is low, because there is no option that is close.  However when there are alternatives and a tool is on the fence of being pushed aside for a new option then it becomes a much higher priority.  I'm just trying to future proof.

The other advantage Rosefire has is that you built it.  I love using in-house tools and that'll never change.  I just want to make sure it continues to be the best tool even when others try to catch up.

**Comment by rockwotj** [comment]
@fisherds 

How does something like this look? Would it look better to have just the R in the navbar, or can you think of anything else to add to it? It feels pretty plain right now.

<img width="403" alt="screen shot 2016-03-20 at 00 05 08" src="https://cloud.githubusercontent.com/assets/8669100/13902799/a5443cfc-ee2f-11e5-9fcd-817bf314b815.png">

Here is google's for reference:

![image](https://cloud.githubusercontent.com/assets/8669100/13902804/03b31a56-ee30-11e5-9371-0bd54dba1b7a.png)

**Comment by rockwotj** [comment]
Also, should there be a consent screen? I think it's pretty obvious by signing in you're giving the person access to your email address and LDAP group (student or instructor, etc).

**Comment by fisherds** [comment]
I like the full logo.  As a reference Rose does have a page like this for Lynda login.  It looks like this...

![2016-03-20_23-13-01](https://cloud.githubusercontent.com/assets/295078/13909967/7ad55d94-eef1-11e5-8bab-a72d0d96a15f.jpg)

So plain it fine.

Also whenever we use the Rose logo in something we should also consult the Rose brand guidelines:
http://www.rose-hulman.edu/offices-and-services/communications-marketing/brand-guidelines.aspx

Page 9 of their PDF: http://www.rose-hulman.edu/media/1707886/RH-BrandGuideLines-20.pdf
is about the only page we care about.  You are good on the clearance requirements.  The size might be a little small.  It says...

Minimum Usage Size by Width = 1.5

Looks like you are at roughly 125 pixels wide, which on an iPhone 5 (smaller phone that is still around) it'd be like 0.8 inches, so technically it should be a little bigger.  I'm flexible on that, but bump it up a little.  V2 goodness is really exciting btw. :)

**Comment by rockwotj** [comment]
I'll bump it up a little, it won't hurt :smile: 

I also got all my logo files from the brand guideline pages, so other than making this a little bigger we should be good. I'm super excited about this! I'm thinking I'll build the android then iOS component, and tackle web last as that should be the hardest...
