### ISSUE TITLE
Create V2 library for iOS

### ISSUE THREAD

**Issue by rockwotj** [rockwotj/rose-firebase-auth#14]

**Comment by rockwotj** [comment]
@fisherds Want to test out the iOS SDK?

Here is the commit where I added it. I also wouldn't mind having you look over the code, as iOS is the area I have least confidence for the SDK, checkout the `swift` branch for the rosefire repo.
https://github.com/rockwotj/FirebasePasswordKeeperiOS/commit/1bd82dbadaa9f3790a2e87160b80c458e6ae6c3b

**Comment by fisherds** [comment]
Will do Tyler.  Might not get done during the week this week though.
Sounds like a good weekend / Monday project.

On Sun, Mar 27, 2016 at 5:15 PM, Tyler Rockwood notifications@github.com
wrote:

> @fisherds https://github.com/fisherds Want to test out the iOS SDK?
> 
> Here is the commit where I added it. I also wouldn't mind having you look
> over the code, as iOS is the area I have least confidence for the SDK,
> checkout the swift branch for the rosefire repo.
> rockwotj/FirebasePasswordKeeperiOS@1bd82db
> https://github.com/rockwotj/FirebasePasswordKeeperiOS/commit/1bd82dbadaa9f3790a2e87160b80c458e6ae6c3b
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/rockwotj/rosefire/issues/14#issuecomment-202146083

## 

Dr. Dave Fisher  | Rose-Hulman  |  fisherds@rose-hulman.com
fisherds@rose-hulman.com  | 812-201-6488
