### ISSUE TITLE
Create V2 library for Web

### ISSUE THREAD

**Issue by rockwotj** [rockwotj/rose-firebase-auth#16]
I'm thinking a redirect is the better experience. @fisherds any input on redirects vs. popups for web OAuth?

**Comment by fisherds** [comment]
I like to mirror what users expect.  So I go looking at sites I like to see what others are doing (to try to figure out what users expect).  So I visited a few to see what I like:

https://www.codecademy.com/ (redirect)
https://creator.zapcode.it/login (popup, had old button)
https://www.firebase.com/login/ (redirect)
https://www.cluekeeper.com/ (redirect, button didn't even say Google)

Yeah I like redirects better.
