### ISSUE TITLE
Create a rosefire-auth Polymer element

### ISSUE THREAD

**Issue by fisherds** [rockwotj/rose-firebase-auth#4]
Similar to the firebase-auth element.  Here is info about that element:
https://github.com/GoogleWebComponents/firebase-element/blob/master/firebase-auth.html

and here is a codelab example of using that element:
https://codelabs.developers.google.com/codelabs/polymer-firebase/index.html?index=..%2F..%2Fpolymer-summit&viewga=UA-39334307-12#3

**Comment by rockwotj** [comment]
I'm guessing this should change to Angular2 service now? :laughing:

**Comment by fisherds** [comment]
In all fairness to Polymer it is still a great tool for creating web components for others.  I just no longer plan to use Polymer unless I'm building a web component for others (which I don't really do).  Pool Polymer.  Angular2 is just too good.  Rolled over like a wave as the core tool.
