### ISSUE TITLE
Can't login - onAuthenticationError: Failed to validate MAC.

### ISSUE THREAD

**Issue by thaisfaria** [rockwotj/rose-firebase-auth#8]
Hi,
Even after generating a new token, I still get the error.

Keys are being sent through e-mail.

Regards,
Thais Faria

**Comment by rockwotj** [comment]
@ThaisFaria thanks for sending it over, I'm looking into the error.

**Comment by rockwotj** [comment]
Switching back to node version 5.3 fixed the issue.
